#!/usr/bin/env bash
# Fetches the GoogleSQL patches this repo applies on top of the pinned
# google/googlesql commit and checks them into patches/googlesql/.
#
# GoogleSQL is pinned in MODULE.bazel to an exact google/googlesql commit
# (upstream, not a fork). The build then applies the patches below via the
# archive_override's `patches` attribute -- so the fixes smallquery needs live
# here as reviewable diffs against upstream instead of as a fork we have to
# rebase. Each patch is an open pull request against fornwall/googlesql; this
# script snapshots the current .patch for each so the checked-in copy is the
# exact bytes Bazel applies.
#
# The PRS list below is the single source of truth: this script both fetches
# the patch files AND rewrites the `patches = [...]` list in MODULE.bazel to
# match (archive_override.patches cannot glob -- labels never expand
# wildcards, and MODULE.bazel has no glob() -- so the list is generated here
# instead of maintained by hand). Order is significant: patches apply top to
# bottom, in PRS order. Re-run this whenever a PR is updated or the list
# changes.
set -euo pipefail

# Pull request numbers on fornwall/googlesql, applied in this order.
PRS=(1 3 4 5)

REPO=fornwall/googlesql
ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="$ROOT/patches/googlesql"
MODULE="$ROOT/MODULE.bazel"

mkdir -p "$OUT_DIR"

# Drop any stale patch files so a PR removed from PRS also leaves patches/.
rm -f "$OUT_DIR"/pull-*.patch

for n in "${PRS[@]}"; do
  url="https://patch-diff.githubusercontent.com/raw/${REPO}/pull/${n}.patch"
  dest="$OUT_DIR/pull-${n}.patch"
  echo "Fetching $url -> ${dest#"$ROOT"/}"
  curl --fail --silent --show-error --location "$url" -o "$dest"
done

# Regenerate the archive_override's `patches = [...]` list in MODULE.bazel from
# PRS, between the generated-block markers, so it can never drift from the
# files above. Everything else in MODULE.bazel is left byte-for-byte untouched.
python3 - "$MODULE" "${PRS[@]}" <<'PY'
import sys

module_path = sys.argv[1]
prs = sys.argv[2:]

begin = "        # BEGIN generated by create-patches.sh -- do not edit by hand\n"
end = "        # END generated by create-patches.sh\n"

lines = ['        "//patches/googlesql:pull-%s.patch",\n' % n for n in prs]
block = [begin, *lines, end]

with open(module_path) as f:
    src = f.readlines()

try:
    i = src.index(begin)
    j = src.index(end)
except ValueError:
    sys.exit(
        "MODULE.bazel is missing the create-patches.sh generated-block markers; "
        "add them inside archive_override's `patches = [` list."
    )

src[i : j + 1] = block
with open(module_path, "w") as f:
    f.writelines(src)
PY

echo "Done. ${#PRS[@]} patch(es) written to ${OUT_DIR#"$ROOT"/} and MODULE.bazel updated."
