#!/usr/bin/env python3
"""Fetches the GoogleSQL patches this repo applies and updates MODULE.bazel.

GoogleSQL is pinned in MODULE.bazel to an exact google/googlesql commit
(upstream, not a fork). The build then applies the patches this script manages
via the archive_override's `patches` attribute -- so the fixes smallquery needs
live here as reviewable diffs against upstream instead of as a fork we have to
rebase. Each patch is an open pull request against fornwall/googlesql; this
script snapshots the current .patch for each so the checked-in copy is the exact
bytes Bazel applies.

The PRS list below is the single source of truth. Running this script:

  - deletes any stale patches/googlesql/pull-*.patch (so dropping a PR from PRS
    removes its file);
  - fetches the current .patch for every PR in PRS into patches/googlesql/;
  - regenerates the `patches = [...]` list in MODULE.bazel, between the
    generated-block markers, from PRS.

archive_override.patches cannot glob (Bazel labels never expand wildcards, and
MODULE.bazel has no glob()), so the list is generated here rather than
maintained by hand. Order is significant: patches apply top to bottom, in PRS
order. Re-run this whenever a PR is updated or the list changes.

Usage: python3 create-patches.py
"""

from __future__ import annotations

import sys
import urllib.error
import urllib.request
from pathlib import Path

# Pull request numbers on fornwall/googlesql, applied in this order.
PRS = [1, 3, 4, 5, 7]

REPO = "fornwall/googlesql"
ROOT = Path(__file__).resolve().parent
OUT_DIR = ROOT / "patches" / "googlesql"
MODULE = ROOT / "MODULE.bazel"

# The generated `patches = [...]` block in MODULE.bazel lives between these two
# marker lines (indented to sit inside the archive_override list).
BEGIN = "        # BEGIN generated by create-patches.py -- do not edit by hand\n"
END = "        # END generated by create-patches.py\n"


def fetch_patches() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("pull-*.patch"):
        stale.unlink()
    for n in PRS:
        url = f"https://patch-diff.githubusercontent.com/raw/{REPO}/pull/{n}.patch"
        dest = OUT_DIR / f"pull-{n}.patch"
        print(f"Fetching {url} -> {dest.relative_to(ROOT)}")
        try:
            with urllib.request.urlopen(url) as resp:
                data = resp.read()
        except urllib.error.URLError as exc:
            sys.exit(f"Failed to fetch {url}: {exc}")
        dest.write_bytes(data)


def update_module() -> None:
    lines = MODULE.read_text().splitlines(keepends=True)
    try:
        i, j = lines.index(BEGIN), lines.index(END)
    except ValueError:
        sys.exit(
            "MODULE.bazel is missing the create-patches.py generated-block "
            "markers; add them inside archive_override's `patches = [` list."
        )
    block = [BEGIN]
    block += [f'        "//patches/googlesql:pull-{n}.patch",\n' for n in PRS]
    block += [END]
    lines[i : j + 1] = block
    MODULE.write_text("".join(lines))


def main() -> None:
    fetch_patches()
    update_module()
    print(
        f"Done. {len(PRS)} patch(es) written to "
        f"{OUT_DIR.relative_to(ROOT)} and MODULE.bazel updated."
    )


if __name__ == "__main__":
    main()
